# Generated by Django 5.0.1 on 2024-02-05 09:33

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_image_delete_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=blog.models.prepend_filename),
        ),
    ]
