# Generated by Django 5.0.1 on 2024-02-03 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['-start_date']},
        ),
    ]
