# Generated by Django 5.0.1 on 2024-02-05 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_destination_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accom_name', models.CharField(max_length=100)),
                ('accom_type', models.CharField(choices=[('Hotels', 'Hotels'), ('Hostel', 'Hostels'), ('Bed and breakfast', 'Bed and breakfast'), ('Guesthouse', 'Guesthouse'), ('Airbnb', 'Airbnb'), ('Apartments', 'Apartments'), ('Resorts', 'Resorts'), ('Camping', 'Camping'), ('Chalets', 'Chalets')], default='Hotels', max_length=20)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.itinerary')),
            ],
        ),
    ]
