# Generated by Django 5.0.1 on 2024-02-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='itinerary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planner.itinerary'),
        ),
    ]
