# Generated by Django 4.2.10 on 2024-02-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_accommodation_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='start_date',
            field=models.DateField(),
        ),
    ]
